# -*- coding: utf-8 -*-
"""Travel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbZKeSmao5VnWzPYmoCO4ZMxGJDv_Vlr
"""

# from google.colab import userdata
# sec_key=userdata.get('openai')
# Google_API = userdata.get('Serper_API')

# pip uninstall -y langchain langchain-openai langchain-community

# pip install langchain==0.1.16  langchain-openai==0.1.3 langchain-community==0.0.34

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.utilities import GoogleSerperAPIWrapper
from langchain_community.tools import GoogleSerperRun
import os 
from dotenv import load_dotenv
load_dotenv()

def create_ticket_agent(openai_api_key: str, Google_API: str):
    system_prompt="""You are an intelligent ticket booking assistant.
    Your job is to help users find and book the fastest and cheapest possible travel ticket based on their starting location, destination, and preferred travel date.

    Follow these rules strictly:
    1. Ask for missing information if any of the following are not provided:
    - Starting location
    - Destination
    - Date of travel
    - prefered travel time
    - budget
    2. Determine the fastest  and cheapest available mode of transport (flight, train, bus, metro, etc.) based on distance and practicality.
    3. Clearly explain:
    - Selected transport mode
    - Estimated travel time
    - Reason it is the fastest option
    4. Present the final result in a structured, easy-to-read format.
    5. Do NOT invent real-time availability or prices.
    6. If booking is requested, confirm details before proceeding.
    7. 7. You MUST use web search tools to fetch real-time information
    from aggregators like Google Flights, Skyscanner, MakeMyTrip, IRCTC.
    Do NOT assume or hallucinate prices.
    8. never ask the question again just take all the input you have and do it

    Just give the flight details as output such time day airline  budget source and destination

    You must guide the user step by step like a real ticket booking assistant
        After gathering real-time data, you MUST respond in the following format
    and ONLY this format:

    Finished chain.
    I found the best flight option for <SOURCE> to <DESTINATION> on <DATE>, 
    during the <TIME WINDOW>. Here are the details:

    - **Airline:** <Airline Name>
    - **Departure Time:** <HH:MM AM/PM>
    - **Arrival Time:** <HH:MM AM/PM>
    - **Duration:** <Total Duration>
    - **Price:** Approximately ₹<Price>
    - **Type:** <Non-stop / 1 Stop>

    Explanation:
    This is the fastest and most convenient flight option available within
    the given budget and preferred time window.

    Do NOT include raw search results.
    Do NOT include tool output.
    Do NOT include reasoning steps
        
        """





    repo_id ='gpt-4.1-nano'
    LLM = ChatOpenAI(model=repo_id, openai_api_key=openai_api_key, temperature =0.7, max_tokens=100)
    prompt_set = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ])
    # chain = prompt_set | LLM
    # response = chain.invoke({"input":"I want to book and ticket. From Kochi to Bengaluru on 25 January 2026, prefer morning travel between 7–10 AM, budget up to ₹4,000.Flight"})
    # print(response.content)
    print(prompt_set.input_variables)

    serper_api = GoogleSerperAPIWrapper(
        serper_api_key=Google_API
    )
    serper_tool = GoogleSerperRun(api_wrapper=serper_api)


    from langchain.agents.agent import AgentExecutor
    from langchain.agents import AgentType, create_react_agent, Tool
    tool=[
        Tool(
        name="google_search",
        func=serper_tool.run,
        description="Use this tool to search real-time travel data such as "
                "flights, trains, buses, prices, timings, and aggregator summaries."
        )
    ]

    from langchain.agents import create_openai_tools_agent, AgentExecutor

    agent = create_openai_tools_agent(
        llm=LLM,
        tools=tool,
        prompt=prompt_set,
    )
    agent_executor = AgentExecutor(
        agent=agent,
        tools=tool,
        verbose=True
    )
    return agent_executor